# Generated by Django 4.1.7 on 2023-04-14 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppShortStories', '0002_alter_genero_estado_alter_shortstories_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortstories',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
