# Generated by Django 4.1.7 on 2023-04-14 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppShortStories', '0003_shortstories_publisher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
