# Generated by Django 4.1.7 on 2023-04-14 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppShortStories', '0004_delete_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortstories',
            name='categoria',
        ),
        migrations.AddField(
            model_name='shortstories',
            name='genero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppShortStories.genero'),
            preserve_default=False,
        ),
    ]
