# Generated by Django 4.1.7 on 2023-04-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppShortStories', '0005_remove_shortstories_categoria_shortstories_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortstories',
            name='estado',
            field=models.BooleanField(),
        ),
    ]
