# Generated by Django 4.1.7 on 2023-04-15 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppShortStories', '0006_alter_shortstories_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creador', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
