# Generated by Django 4.1.7 on 2023-04-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppShortStories', '0007_genero_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortstories',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cuentos'),
        ),
    ]
