# Generated by Django 4.1.7 on 2023-04-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppShortStories', '0010_shortstories_creado_el'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='apellido',
            field=models.CharField(default=505.75, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=505.75, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='nombre',
            field=models.CharField(default=505.75, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='telefono',
            field=models.CharField(default=505.75, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shortstories',
            name='texto',
            field=models.CharField(max_length=200),
        ),
    ]
