# Generated by Django 4.1.7 on 2023-04-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppShortStories', '0012_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='motivo',
            field=models.IntegerField(choices=[(1, 'Problemas en la Registracion'), (2, 'Problemas al Loguearse'), (3, 'Problemas en la App'), (4, 'Otros')], default=1),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='user_name',
            field=models.TextField(max_length=50),
        ),
    ]
