# Generated by Django 4.1.7 on 2023-04-19 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppShortStories', '0014_alter_mensaje_motivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='user_name',
        ),
    ]
