# Generated by Django 4.1.7 on 2023-04-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppShortStories', '0015_remove_mensaje_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'En proceso'), (3, 'Cerrado'), (4, 'Derivado')], default=1),
        ),
    ]
