# Generated by Django 4.1.7 on 2023-04-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppShortStories', '0016_mensaje_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='motivo',
            field=models.IntegerField(blank=True, choices=[(1, 'Consulta sobre la App'), (2, 'Problemas en la Registracion'), (3, 'Problemas al Loguearse'), (4, 'Problemas en la App'), (5, 'Publicacion Ofensiva'), (6, 'Otros')], default=1, null=True),
        ),
    ]
